apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 100Mi  # Adjust this as needed, don't allocate too much storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"  # Path on the host (use this only for local development)
